- name: Download wordpress
  get_url:
    url:  https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy file with owner and permissions
  copy:
    src: /tmp/wordpress/.
    dest: /var/www/html
    owner: apache
    group: apache
    mode: '0755'   
    remote_src: yes 

- name: Template a file to /var/www/html
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php

- name: Enable Apache
  service:
    name: httpd
    state: restarted    